# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Get OS type
OS="xxx"
case $(uname) in
    'Darwin') 
        OS='macOS'
        ;;
    'Linux')
        OS='Linux'
        esac
# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="spaceship"
# ZSH_THEME="robbyrussell"

# Spaceship options
SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  golang        # Go section
  pyenv         # Pyenv section
  gcloud        # gcloud
  kubectl # kube context
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

SPACESHIP_KUBECTL_SHOW="true"
SPACESHIP_KUBECTL_VERSION_SHOW="false"
SPACESHIP_KUBECTL_COLOR="cyan"
SPACESHIP_KUBECTL_VERSION_PREFIX=""
# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git 
  docker 
  colorize 
  autojump
  golang
  sudo 
  command-not-found 
  zsh-completions 
  zsh-autosuggestions 
  zsh-syntax-highlighting
  pyenv
  )
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=180'
source $ZSH/oh-my-zsh.sh

# pyenv disable prompt
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run alias.
#
# Example aliases
alias zshconfig="nvim ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
for file in ~/.{aliases,functions}; do
     [ -r "$file" ] && [ -f "$file" ] && source "$file";
 done;
 unset file;

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

ORIGINAL_PATH=/usr/local/bin:/usr/local/go/bin:/usr/bin:/usr/sbin:/sbin:/bin
export GOPATH=$HOME/go
export SNAP=/snap/bin
export PATH=$HOME/.jenv/bin:$GOPATH/bin:${SNAP}:${HOME}/.krew/bin:$ORIGINAL_PATH
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home

export HOMEBREW_NO_AUTO_UPDATE=1

# This speeds up pasting w/ autosuggest
# https://github.com/zsh-users/zsh-autosuggestions/issues/238
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need .url-quote-magic?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish


# kubectl config
alias k='kubectl'
alias kcd='kubectl config set-context $(kubectl config current-context) --namespace '
alias kwru='kubectl config current-context'
alias kwn='kubectl config get-contexts'
alias kis='kubectl --insecure-skip-tls-verify'


# kubectl autocompletion
source <(kubectl completion zsh)
complete -F __start_kubectl k

#istioctl config
alias istio=istioctl

# for jenv
# eval "$(jenv init -)"
# eval "$(jenv enable-plugin export)"

# for pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
# export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv virtualenv-init -)"
export LDFLAGS="-L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib"
export CPPFLAGS="-I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include"

if [[ $OS == "Linux" ]]; then
  source /usr/share/doc/fzf/examples/key-bindings.zsh
  source /usr/share/doc/fzf/examples/completion.zsh
else
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
fi


complete -o nospace -C /usr/local/bin/kustomize kustomize

# if [ ! "$TMUX" = ""  ]; then export TERM=xterm-256color; 
# if [ ! "$TMUX" = ""  ]; then 
#   if [[ $OS == "macOS" ]]; then
#     export TERM="tmux-256color"
#   else
#     export TERM="xterm-256color"; 
#   fi
# else 
#   export TERM="xterm-256color";
# fi

export BAT_THEME="Solarized (Dark)"

# pbcopy pbpaste
if [[ $OS == "Linux" ]]; then
  alias pbcopy='xclip -selection clipboard'
  alias pbpaste='xclip -selection clipboard -o'
  alias suspend='systemctl suspend'
  alias toodark='lookandfeeltool -a com.github.vinceliuice.Orchis > /dev/null 2>&1'
  alias toobright='lookandfeeltool -a com.github.vinceliuice.Orchis-dark > /dev/null 2>&1'
fi 

# docker aliases
alias drmi='docker rmi $(docker images | grep '"'"'^<none>'"'"'| awk '"'"'{print $3}'"'"')'

# find pod ip
alias findpod='kubectl get pods -A -o wide | grep '
alias findsvc='kubectl get services -A -o wide | grep '



# gcp tools
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc


for file in ~/.bash_{aliases,functions}
do
    if [[ -f "$file" ]]
    then
        source "$file"
    fi
done

export USE_GKE_GCLOUD_AUTH_PLUGIN=True
export PATH="/usr/local/opt/libpq/bin:$PATH"

# see https://github.com/golang/go/issues/35164#issuecomment-632702878
export GOPRIVATE=source.golabs.io


alias tf=terraform
if [ -n "$RANGER_LEVEL" ]; then export PS1="[ranger]$PS1"; fi

## add cargo
export PATH="$HOME/.cargo/bin:$PATH"
export FZF_DEFAULT_OPTS='--multi'

## add poetry
export PATH="/Users/shide.foo/.local/bin:$PATH"

export XDG_CONFIG_HOME=~/.config
export XDG_RUNTIME_DIR=/tmp/.runtime

## add mason to path
export PATH="$PATH:/Users/shide.foo/.local/share/nvim/mason/bin"
